[package]
name = "easy_reader"
version = "0.1.1"
authors = ["Michele Federici (@ps1dr3x) <michele@federici.tech>"]
description = "Move forward, backward or randomly through the lines of huge files. Easily and fastly."
repository = "https://github.com/ps1dr3x/easy_reader"
license = "Apache-2.0"
keywords = ["reader", "lines", "huge", "random", "backwards"]
readme="README.md"

[dependencies]
rand = "0.4.2"
